### ISSUE TITLE
Document the privacy trade off of using non-ISP upstream DNS

### ISSUE THREAD

**Issue by phixion** [yegle/your-dns#5]
Isnt adding two more parties (hoster and google) to your hole DNS game counterproductive securitywise? 

Since my ISP is able to see my dns traffic anyway (until ESNI is a thing) I would rather peer their DNS for probably the best speed and least amount 3rd party involvement

**Comment by yegle** [comment]
The alternative is to do recursive query to each domain's authoritative name server, which is very likely over plaintext DNS query (I'm not even sure any DNS software support doing recursive query over TLS/HTTPS) and prone to MitM attack (think of those search result when you type a wrong domain).

I don't understand the setup described in this repo would reduce security. It might reduce the privacy by exposing the list of websites to upstream DNS.

In any case, setting your ISP DNS as your upstream DNS may still be a good option. I'll see if I can update the README with this information.

**Comment by phixion** [comment]
privacy is what I meant, not security - sorry. otherwise straight forward project here, I like it!
